[package]
name = "splr"
version = "0.4.0-dev0.4.1"
authors = ["Narazaki Shuji <shujinarazaki@protonmail.com>"]
description = "A modern CDCL SAT solver in Rust"
edition = "2018"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/shnarazk/splr"
homepage = "https://github.com/shnarazk/splr"
keywords = ["SAT", "SAT-solver", "logic", "satisfiability"]
categories = ["mathematics", "science"]

[dependencies]
bitflags = "1.2"
copyless = "0.1"
libc = "0.2"
structopt = "0.3"

[features]
default = [] # 
boundary_check = []
EVSIDS = []
ema_calibration = []
no_IO = []
trace_analysis = []
trace_elimination = []

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
