[package]
name = "splr"
version = "0.6.0-RC0"
authors = ["Narazaki Shuji <shujinarazaki@protonmail.com>"]
description = "A modern CDCL SAT solver in Rust"
edition = "2018"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/shnarazk/splr"
homepage = "https://github.com/shnarazk/splr"
keywords = ["SAT", "SAT-solver", "logic", "satisfiability"]
categories = ["mathematics", "science"]

[dependencies]
bitflags = "1.2"

[features]
default = ["prefer_best_phase"]
boundary_check = []
ema_calibration = []
EVSIDS = []
explore_timestamp = []
incremental_solver = []
moving_var_reward_rate = []
no_IO = []
prefer_best_phase = []
progress_ACC = []
rephase_only_reason_vars = []
progress_MLD = []
temp_order = []
trace_analysis = []
trace_elimination = []

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
