[package]
name = "splr"
version = "0.4.2-dev.0"
authors = ["Narazaki Shuji <shujinarazaki@protonmail.com>"]
description = "A modern CDCL SAT solver in Rust"
edition = "2018"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/shnarazk/splr"
homepage = "https://github.com/shnarazk/splr"
keywords = ["SAT", "SAT-solver", "logic", "satisfiability"]
categories = ["mathematics", "science"]

[dependencies]
bitflags = "1.2"
libc = { version = "0.2", optional = true }
clap = { version = "3.0.0-beta.1", optional = true }

[[bin]]
name = "dmcr"
required-features = ["libc", "clap"]

[[bin]]
name = "splr"
required-features = ["libc", "clap"]

[features]
default = ["cli"]
cli = ["libc", "clap"]
boundary_check = []
ema_calibration = []
EVSIDS = []
incremental_solver = []
no_IO = []
temp_order = []
trace_analysis = []
trace_elimination = []

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
