[package]
name = "splr"
version = "0.1.4"
authors = ["Shuji Narazaki <shujinarazaki@protonmail.com>"]
about = "SAT solver for Propositional Logic in Rust"
description = "A pure rustic CDCL SAT solver based on Glucose"
edition = "2018"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/shnarazk/splr"
root_url = "https://docs.rs/splr/0.1.4"
homepage = "https://github.com/shnarazk/splr"
keywords = ["SAT", "SAT-solver", "logic"]
categories = ["science"]

[dependencies]
bitflags = "1.1"
copyless = "0.1"
libc = "0.2"
structopt = "0.3"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
